### ISSUE TITLE
Connection for GL3000

### ISSUE THREAD

**Issue by knapeto** [jaayesta/queclink-parser#1]
Hi,

i found your awesome lib, thanks you very much for sharing. How you connect you device to PC? I dont have Data_Cable_M by I have just basic mini usb cabel.

Thanks for reply

**Comment by jaayesta** [comment]
Hey knapeto, 
Thanks, I hope it's useful for you.
You need to fabricate your own cable with a RS232. You can find the instructions in point 3.6 (UART Interface) of GV200 User Manual
![uart](https://cloud.githubusercontent.com/assets/1934068/17556283/d3f0ad8e-5ee0-11e6-9be0-9f3659ad2f65.png)
