### ISSUE TITLE
Temperature Sensor data not parsed 

### ISSUE THREAD

**Issue by ahmedsoliman64** [jaayesta/queclink-parser#12]
Devices with temperature sensor no data parsed

**Comment by jaayesta** [comment]
The data from temperature came within externalData, 
For example, the temperature of the temp sensor id 28A340C50800006F is 5.25℃:
`"+RESP:GTERI,350401,867844003113282,,00000002,13151,10,1,1,0.0,0,835.3,-70.589656,-32.852054,20180720014258,0730,0002,7440,6EBA,00,87745.9,03148:38:16,,,,00,00,2,1,28A340C50800006F,1,0054,20180720014513,0040$"
{
	raw: '+RESP:GTERI,350401,867844003113282,,00000002,13151,10,1,1,0.0,0,835.3,-70.589656,-32.852054,20180720014258,0730,0002,7440,6EBA,00,87745.9,03148:38:16,,,,00,00,2,1,28A340C50800006F,1,0054,20180720014513,0040$',
	manufacturer: 'queclink',
	device: 'Queclink-GV200',
	type: 'data',
	imei: '867844003113282',
	protocolVersion: { raw: '350401', deviceType: 'GV200', version: '4.1' },
	temperature: null,
	history: false,
	sentTime: 2018-07-20T01:45:13.000Z,
	serialId: 64,
	alarm: { type: 'Gps' },
	loc: { type: 'Point', coordinates: [ -70.589656, -32.852054 ] },
	speed: 0,
	gpsStatus: true,
	hdop: 1,
	status: { 
		raw: '0000',
		sos: false,
		input: { '1': false, '2': false, '3': false, '4': false },
		output: { '1': false, '2': false, '3': false, '4': false },
		charge: true 
	},
	azimuth: 0,
	altitude: 835.3,
	datetime: 2018-07-20T01:42:58.000Z,
	voltage: { 
		battery: null,
		inputCharge: 13.151,
		ada: null,
		adb: null,
		adc: null 
	},
	mcc: 730,
	mnc: 2,
	lac: 29760,
	cid: 28346,
	odometer: 87745.9,
	hourmeter: 3148.637777777778,
	externalData: { 
		eriMask: { 
			raw: '00000002',
			digitFuelSensor: false,
			AC100: true,
			reserved: false,
			fuelLevelPercentage: false,
			fuelVolume: false 
		},
		uartDeviceType: 'AC100 1 Wire Bus',
		fuelSensorData: null,
		AC100Devices: [ 
			{ 
				deviceNumber: '28A340C50800006F',
				deviceID: '1',
				deviceData: 5.25 
			} 
			]
		} 
	}	
}`

**Comment by ahmedsoliman64** [comment]
@jaayesta thanks for your fast reply, but the device itself didn't send this type of response RESP:GTERI, have i to configure something to allow it send this message
