### ISSUE TITLE
Unknown type for GV500MAP Device

### ISSUE THREAD

**Issue by faustroxas** [jaayesta/queclink-parser#23]
Receiving 'type':'unknown' when trying with GV500MAP device

`{
'type':UNKNOWN,
'raw':'+RESP:GTGSM,5E0100,864431042549834,,GV500MAP,FRI,0515,0002,4EF6,8167,9,,0515,0002,4EF6,8167,9,,0515,0002,4EF6,3347,10,,0515,0002,4EF6,0BFF,7,,0515,0002,4EF6,8648,5,,0515,0002,4EF6,1118,8,,0515,0002,4EF6,A83F,14,00,20210721033927,47E6$'
}`

**Comment by mpanichella** [comment]
I have the same problem, to resolve this you need to add 
    `else if (device === 'GV500' **|| device === 'GV500MAP'**) {
      result = gv500.parse(raw.toString())
    }`
in the index.js
and 

'5E': 'GV500MAP',

into the file utils, devices dictionary.

The parser is the same that the GV500, I used and working fine

**Comment by jaayesta** [comment]
Thanks @mpanichella ! I just added your suggestion.
