### ISSUE TITLE
Tests data

### ISSUE THREAD

**Issue by knapeto** [jaayesta/queclink-parser#3]
Hi,

this is some data from GL300 for debugging.
Thanks you for amazing work!

{"type":"UNKNOWN","raw":"+RESP:GTGSM,300301,860599001099076,FRI,0230,0003,959c,3c20,47,,0230,0003,959c,32fb,42,,0230,0003,959c,32fc,25,,0230,0003,959c,27b2,25,,0230,0003,959c,3373,19,,,,,,,,0230,0003,959c,3c1f,31,00,20160819133321,AC2F$"}{"type":"UNKNOWN","raw":"+RESP:GTFRI,300301,860599001099076,GL300,0,0,1,0,,,,14.466820,50.020033,20160819054005,,,,,,43,,AC30$"}{"type":"UNKNOWN","raw":"+RESP:GTGSM,300301,860599001099076,FRI,0230,0003,959c,3c20,47,,0230,0003,959c,32fb,44,,0230,0003,959c,27b2,25,,0230,0003,959c,32fc,22,,0230,0003,959c,3373,20,,,,,,,,0230,0003,959c,3c1f,31,00,20160819133326,AC31$"}{"type":"UNKNOWN","raw":"+RESP:GTFRI,300301,860599001099076,GL300,0,0,1,0,,,,14.466820,50.020033,20160819054005,,,,,,43,,AC32$"}{"type":"UNKNOWN","raw":"+RESP:GTSOS,300301,860599001099076,GL300,0,0,1,0,4.1,312,282.4,14.466820,50.020033,20160819054005,0230,0003,959C,3C1F,,43,20160819133326,AC33$"}{"type":"UNKNOWN","raw":"+RESP:GTGSM,300301,860599001099076,SOS,0230,0003,959c,3c20,47,,0230,0003,959c,32fb,44,,0230,0003,959c,27b2,25,,0230,0003,959c,32fc,22,,0230,0003,959c,3373,20,,,,,,,,0230,0003,959c,3c1f,31,00,20160819133326,AC34$"}{"type":"UNKNOWN","raw":"+RESP:GTINF,300301,860599001099076,GL300,41,8942031016172273736f,31,0,0,0.0,,3.74,0,0,0,0,0,20160819054005,43,,45.0,,,20160819133326,AC35$"}{"type":"UNKNOWN","raw":"+RESP:GTGSM,300301,860599001099076,FRI,0230,0003,959c,3c20,46,,0230,0003,959c,32fb,45,,0230,0003,959c,27b2,24,,0230,0003,959c,32fc,23,,0230,0003,959c,3373,21,,,,,,,,0230,0003,959c,3c1f,31,00,20160819133330,AC36$"}{"type":"UNKNOWN","raw":"+RESP:GTFRI,300301,860599001099076,GL300,0,0,1,0,,,,14.466820,50.020033,20160819054005,,,,,,43,,AC37$"}{"type":"UNKNOWN","raw":"+RESP:GTGSM,300301,860599001099076,FRI,0230,0003,959c,3c20,45,,0230,0003,959c,32fb,40,,0230,0003,959c,27b2,23,,0230,0003,959c,32fc,22,,0230,0003,959c,3373,22,,,,,,,,0230,0003,959c,3c1f,31,00,20160819133335,AC38$"}{"type":"UNKNOWN","raw":"+RESP:GTFRI,300301,860599001099076,GL300,0,0,1,0,,,,14.466820,50.020033,20160819054005,,,,,,43,,AC39$"}{"type":"UNKNOWN","raw":"+RESP:GTGSM,300301,860599001099076,FRI,0230,0003,959c,3c20,42,,0230,0003,959c,32fb,38,,0230,0003,959c,27b2,23,,0230,0003,959c,3373,22,,0230,0003,959c,32fc,21,,,,,,,,0230,0003,959c,3c1f,31,00,20160819133340,AC3A$"}{"type":"UNKNOWN","raw":"+RESP:GTFRI,300301,860599001099076,GL300,0,0,1,0,,,,14.466820,50.020033,20160819054005,,,,,,43,,AC3B$"}

**Comment by jaayesta** [comment]
Hi knapeto,

Thanks for your data. There is no support for GL300 devices in the parser jet. As soon as I add it, I'll let you know.

Cheers

**Comment by jaayesta** [comment]
Hi knapeto,

GL300 is already supported.

\m/
